# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Tests

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: volta-cli/action@v4
            - run: node -v
            - run: yarn -v
            - run: printenv
            - run: ls -la
            - run: yarn install
            - run: yarn test
            - run: yarn test --coverage
            - run: yarn generate-coverage
